### ISSUE TITLE
uninitialized constant while trying to run examples

### ISSUE THREAD

**Issue by grych** [cie/rubylog#2]
Hi,
This is a great idea to implement Prolog in Ruby! However, when I am trying to run the examples, I am having uninitialized constant error, like:

```
rubylog1.rb:8:in `block in <main>': uninitialized constant N (NameError)
    from /Users/grych/.rvm/gems/ruby-1.9.3-p385/gems/rubylog-1.0.0/lib/rubylog/theory.rb:121:in `instance_exec'
    from /Users/grych/.rvm/gems/ruby-1.9.3-p385/gems/rubylog-1.0.0/lib/rubylog/theory.rb:121:in `with_context'
    from /Users/grych/.rvm/gems/ruby-1.9.3-p385/gems/rubylog-1.0.0/lib/rubylog/theory.rb:35:in `theory'
    from /Users/grych/.rvm/gems/ruby-1.9.3-p385/gems/rubylog-1.0.0/lib/rubylog/mixins/kernel.rb:3:in `theory'
    from rubylog1.rb:3:in `<main>'
```

I am running ruby 1.9.3p385

**Comment by EHadoux** [comment]
Hello, it has been a while.
Do you plan to support Ruby 2 on day or do you know a alternative to rubylog?
Unfortunately, every stuff I've found are either too old or not as powerful :(
For instance, I have predicates ```attack(a,b), attack(b,c)``` but I cannot express a rule like 
```
dominated(X) :- attack(Y,X), a_way_to_say_there_is_no_Z_such_as_attack(Z,Y)
```

**Comment by cie** [comment]
Hello,

First of all, I'm so happy that someone is using my language! I'm not using it currently in any active project, so I'm not working on it for my own benefit. However, if I can help you with any answers, bug fixes or small features, I'd be happy to do so.

Rubylog does support Ruby 2, I just didn't update the Readme until now (now I did). But I'm not sure I understand your concern. Did this cause you a block? Then sorry for my lack of communication. As I understood from your [comment](https://github.com/cie/rubylog/issues/2#issuecomment-29060687), you managed to use Rubylog with the `extend Rubylog::Context`. The standard way to use it is this:

```
require "rubylog"
module MyRubylogCode
  extend Rubylog::Context

  # your rubylog code here
end
```

Another way is to use the `rubylog` executable with a file that contains Rubylog code:

```
$ rubylog myfile.rb
```

This is the way you can run the examples too.

Rubylog is quite under-documented because this was my BSc thesis work, and as I got closer to the deadline, I rather worked on the code and the thesis, not the documentation. And now, as I don't use Rubylog anymore, it's a bit orphaned :)

BTW, is your project Open Source? I would be happy to see your Rubylog code, and maybe I could give you some suggestions too.

**Comment by EHadoux** [comment]
You're right, I'm sorry.
I had the `uninitialized constant` stuff while using the extend way, so I assumed it was a version problem but it may have been a human problem.
Anyway, this is working!
My code is open sourced but the Rubylog is not inside yet, i'll drop the link here when it will be. 
Thanks very much :)

**Comment by cie** [comment]
You're welcome :)
